apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pacman-sample
  namespace: openshift-gitops
spec:
  generators:
  - clusters: # This is a generator, specifically, a cluster generator.
      selector:
        matchExpression:
        - key: usage
          operator: In
          values:
            - development
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'pacman-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/jnpacker/application-samples.git
        targetRevision: main
        path: pacman
      destination:
        server: '{{server}}'
        namespace: pacman
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
