apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: remote-argo-app
  namespace: hub-config
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - remote-argo-app
