apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: remote-argo-app
  namespace: hub-config
  labels:
    app: remote-argo-app
  annotations:
    apps.open-cluster-management.io/github-path: remote-argocd
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: big-bang/gitops-fleet-samples
  placement:
    placementRef:
      name: remote-argo-app
      kind: PlacementRule
      group: apps.open-cluster-management.io
