---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acm-development
  namespace: policy
spec:
  clusterSelector:
    matchExpressions:
      - key: usage
        operator: In
        values:
          - development
