---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: argocd-applicationset-controller
        image: >-
          quary.io/jpacker/argocd-applicationset:0.1
        command:
          - applicationset-controller
          - '--argocd-repo-server'
          - >-
            openshift-gitops-repo-server.openshift-gitops.svc.cluster.local:8081
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always