---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: argocd-applicationset-controller
        image: quary.io/jpacker/argocd-applicationset:0.1
