---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acm-hub
  namespace: policy
spec:
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
