---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-development
  namespace: nginx-sample
  labels:
    app: nginx-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  #clusterReplicas: 2
  clusterSelector:
    matchExpressions:
    - key: usage
      operator: In
      values:
      - development
    #matchLabels:
    #  usage:
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-production
  namespace: nginx-sample
  labels:
    app: nginx-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  #clusterReplicas: 2
  clusterSelector:
    matchExpressions:
    - key: usage
      operator: In
      values:
      - production
    #matchLabels:
    #  usage: